### ISSUE TITLE
Provide a readme with the problem's definition

### ISSUE THREAD

**Issue by aburakayaz** [aburakayaz/MagicVowels#1]
I wasn't able to find the problem's definition anywhere. I saw it on HackerRank and then never seen it again. Can you make a PR with the problem definition?

**Comment by szarroug3** [comment]
Can I take this?

**Comment by aburakayaz** [comment]
Sure @szarroug3, just make a pr when you prepare the file. But I will keep this issue open for grabs since the task requires research.

**Comment by szarroug3** [comment]
@aburakayaz I'm trying to push to a branch but I have permission denied.

**Comment by szarroug3** [comment]
Oh nevermind, I'll fork.
